### ISSUE TITLE
Mida-mida-Pi-Ra-Mi-Da

### ISSUE THREAD

**Issue by MrIlie** [Vasile2k/vas-chat-reactor#2]
Good.
You can read so you're not blind.

**Comment by Vasile2k** [comment]
We will fix tat issue in next update.

**Comment by MrIlie** [comment]
Don't eat mamaligă with sarmale because borală
Eat mamaligă with brânză, because it's tasty, and it smells like an old sponge filled with fairy farts.

Thank you for reading this, and be careful, fairy farts are everywhere !

**Comment by Vasile2k** [comment]
Problem fixed now!
